version: '3.7'

services:
  # Build the app services
  app:
    build: app
  nginx:
    container_name: nginx
    build: nginx
    # Bind the port 80 of container to machine port 80
    ports:
      - 443:443
    # Make app as nginx dependency service
    depends_on:
      - app
  client:
    build: client
    command: python ./client.py
    network_mode: host
